In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [5]:
ds = pd.read_csv('winequality-red.csv')
ds

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [6]:
ds.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [7]:
ds.shape

(1599, 12)

In [8]:
ds.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [9]:
y = ds.quality
x = ds.drop('quality', axis=1)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3,random_state=111,stratify=y)

In [11]:
# Standardization
x_train_scaled = preprocessing.scale(x_train)
x_train_scaled

array([[ 0.91168023,  1.13222431,  0.80083432, ..., -1.02323948,
        -0.53259588,  0.52107073],
       [ 0.74440265,  0.12514716, -0.52858904, ..., -1.08754754,
        -0.2822389 , -0.95355985],
       [ 0.52136588, -0.88192999,  0.85196599, ..., -0.44446696,
         0.969546  ,  0.33674191],
       ...,
       [-1.54172422,  0.48881391, -1.39782738, ...,  1.74200703,
        -0.84554211, -0.49273779],
       [-0.37078119,  1.24412177, -0.01727236, ..., -0.44446696,
        -1.28366683, -1.04572426],
       [-0.76109553,  2.5029682 , -1.19330071, ...,  0.26292169,
        -0.34482815, -0.95355985]])

In [12]:
x_train_scaled.mean(axis=0)

array([ 5.73863268e-16, -1.11121518e-16,  5.39733088e-17,  5.71482093e-17,
       -1.84144230e-16,  8.73097642e-18,  6.66729109e-17, -1.58951394e-14,
       -4.38771251e-15,  1.26202296e-16, -6.52442056e-16])

In [13]:
x_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#Cross validation Pipeline:
scaler = preprocessing.StandardScaler().fit(x_train)

In [15]:
x_train_scaled = scaler.transform(x_train)

In [16]:
x_train_scaled.mean(axis=0)

array([ 5.73863268e-16, -1.11121518e-16,  5.39733088e-17,  5.71482093e-17,
       -1.84144230e-16,  8.73097642e-18,  6.66729109e-17, -1.58951394e-14,
       -4.38771251e-15,  1.26202296e-16, -6.52442056e-16])

In [17]:
x_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
x_test_scaled = scaler.transform(x_test)
x_test_scaled.mean(axis=0)

array([-0.08420217,  0.00351695, -0.04092076, -0.05840553,  0.08278128,
       -0.14078784, -0.03968702, -0.01433399,  0.04280056,  0.06369707,
       -0.03575592])

In [21]:
x_test_scaled.std(axis=0)

array([0.89526952, 1.00499383, 0.98514009, 0.81161148, 1.31574843,
       0.85613274, 0.9679061 , 0.90336649, 0.97419788, 1.18875515,
       0.93773011])

In [22]:
pipeline = make_pipeline(preprocessing.StandardScaler(),RandomForestRegressor(n_estimators=120))

In [23]:
# Hyperparameter
pipeline.get_params()

{'memory': None,
 'steps': [('standardscaler',
   StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('randomforestregressor',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                         max_features='auto', max_leaf_nodes=None,
                         min_impurity_decrease=0.0, min_impurity_split=None,
                         min_samples_leaf=1, min_samples_split=2,
                         min_weight_fraction_leaf=0.0, n_estimators=120,
                         n_jobs=None, oob_score=False, random_state=None,
                         verbose=0, warm_start=False))],
 'verbose': False,
 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True),
 'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                       max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1,

In [24]:
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],'randomforestregressor__max_depth': [None,4,2,1]}

In [26]:
# cross-validation
rp= GridSearchCV(pipeline,hyperparameters, cv=9)
rp.fit(x_train, y_train)

GridSearchCV(cv=9, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split=

In [27]:
rp.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'log2'}

In [28]:
# confirming Model be Retained
rp.refit

True

In [29]:
# start predicting the data 
y_pred = rp.predict(x_test)

In [30]:
#Apply metrics on the completed Model
r2_score(y_test, y_pred)

0.4536499860529988

In [31]:
mean_squared_error(y_test, y_pred)

0.35421455439814814

In [32]:
# To save the model
joblib.dump(rp, 'rf_regressor.pkl')

['rf_regressor.pkl']

In [33]:
# To load the model from pickle file
rp2 = joblib.load('rf_regressor.pkl')

In [35]:
rp2.predict(x_test)

array([5.13333333, 5.54166667, 6.2       , 5.225     , 5.73333333,
       5.825     , 5.88333333, 6.95833333, 5.45      , 5.68333333,
       5.51666667, 5.25833333, 6.13333333, 5.35833333, 5.28333333,
       5.25      , 5.40833333, 5.13333333, 5.40833333, 4.91666667,
       5.94166667, 6.43333333, 5.9       , 5.525     , 5.225     ,
       5.68333333, 5.825     , 5.775     , 5.925     , 5.325     ,
       5.5       , 5.18333333, 5.19166667, 5.20833333, 5.18333333,
       4.93333333, 5.90833333, 5.39166667, 5.85833333, 5.6       ,
       5.15833333, 4.88333333, 5.28333333, 5.09166667, 4.85833333,
       5.55833333, 5.625     , 5.25833333, 5.475     , 5.95833333,
       6.39166667, 5.33333333, 6.73333333, 5.93333333, 5.225     ,
       6.84166667, 6.20833333, 6.00833333, 5.73333333, 5.66666667,
       5.15833333, 5.76666667, 5.06666667, 5.88333333, 5.33333333,
       6.58333333, 6.15      , 6.93333333, 5.76666667, 5.25      ,
       5.375     , 5.9       , 6.68333333, 6.525     , 5.86666